Traceback (most recent call last):
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 446, in <module>
    main()
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 405, in main
    model = _create_model(get_d_in_raw())
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 389, in get_d_in_raw
    gp = next(dl)
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 114, in data_loader_wrapper
    for gp in data_loader:
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 198, in get_data_loader_imsm
    dataset, subgroup, path_indices)
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 380, in _get_imsm_paths
    f'{num_pairs} {len_qgraphs_paths} {qgraphs_paths} {dataset}, {subgroup}, ' \
AssertionError: 100 0 [] imsm-dblp_unlabeled, dense_64, 100 qp=/home/kli16/NSUBS/model/SubgraphMatching/dataset/dblp_unlabeled/query_graph/query_dense_64_*.graph

