Critical! Fix random seed for torch and numpy
Traceback (most recent call last):
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 446, in <module>
    main()
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 405, in main
    model = _create_model(get_d_in_raw())
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 389, in get_d_in_raw
    gp = next(dl)
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 114, in data_loader_wrapper
    for gp in data_loader:
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 198, in get_data_loader_imsm
    dataset, subgroup, path_indices)
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 385, in _get_imsm_paths
    assert len(qgraphs_paths) == num_pairs
AssertionError

Total time: 6.376 secs
/home/kli16/NSUBS/model/OurSGM/logs/our_test_imsm-dblp_unlabeled_dense_64_nn_300_2023-10-09T08-12-08.713555
our_test_imsm-dblp_unlabeled_dense_64_nn_300_2023-10-09T08-12-08.713555
