Critical! Fix random seed for torch and numpy
Take 100 out of 200 query graphs
Loaded target graph, initial features, and encoder from /home/kli16/NSUBS/model/OurSGM/save/imsm-dblp_unlabeled_dense_64/target.pickle
Traceback (most recent call last):
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 446, in <module>
    main()
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 405, in main
    model = _create_model(get_d_in_raw())
  File "/home/kli16/NSUBS/model/OurSGM/main.py", line 389, in get_d_in_raw
    gp = next(dl)
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 114, in data_loader_wrapper
    for gp in data_loader:
  File "/home/kli16/NSUBS/model/OurSGM/data_loader.py", line 240, in get_data_loader_imsm
    gq = read_tve(qpn)
  File "/home/kli16/miniconda3/envs/NSUBS_env/lib/python3.7/site-packages/networkx/utils/decorators.py", line 795, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 5, in argmap_read_tve_1
    import warnings
  File "/home/kli16/NSUBS/model/OurSGM/read_tve_imsm.py", line 16, in read_tve
    for line in lines:
  File "/home/kli16/NSUBS/model/OurSGM/read_tve_imsm.py", line 8, in <genexpr>
    lines = (line.decode(encoding) for line in path)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Total time: 5.146 secs
/home/kli16/NSUBS/model/OurSGM/logs/our_test_imsm-dblp_unlabeled_dense_64_nn_300_2023-10-09T18-36-23.083683
our_test_imsm-dblp_unlabeled_dense_64_nn_300_2023-10-09T18-36-23.083683
